/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package won;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-02-27")
public class MasterCheckModel implements org.apache.thrift.TBase<MasterCheckModel, MasterCheckModel._Fields>, java.io.Serializable, Cloneable, Comparable<MasterCheckModel> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MasterCheckModel");

  private static final org.apache.thrift.protocol.TField DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("data", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField MASTERS_FIELD_DESC = new org.apache.thrift.protocol.TField("masters", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField SYS_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("sys_status", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MasterCheckModelStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MasterCheckModelTupleSchemeFactory();

  public java.util.List<java.util.List<java.lang.String>> data; // required
  public java.util.List<java.util.List<java.lang.String>> masters; // required
  public long sys_status; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DATA((short)1, "data"),
    MASTERS((short)2, "masters"),
    SYS_STATUS((short)3, "sys_status");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DATA
          return DATA;
        case 2: // MASTERS
          return MASTERS;
        case 3: // SYS_STATUS
          return SYS_STATUS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SYS_STATUS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DATA, new org.apache.thrift.meta_data.FieldMetaData("data", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.MASTERS, new org.apache.thrift.meta_data.FieldMetaData("masters", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.SYS_STATUS, new org.apache.thrift.meta_data.FieldMetaData("sys_status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MasterCheckModel.class, metaDataMap);
  }

  public MasterCheckModel() {
  }

  public MasterCheckModel(
    java.util.List<java.util.List<java.lang.String>> data,
    java.util.List<java.util.List<java.lang.String>> masters,
    long sys_status)
  {
    this();
    this.data = data;
    this.masters = masters;
    this.sys_status = sys_status;
    setSys_statusIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MasterCheckModel(MasterCheckModel other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetData()) {
      java.util.List<java.util.List<java.lang.String>> __this__data = new java.util.ArrayList<java.util.List<java.lang.String>>(other.data.size());
      for (java.util.List<java.lang.String> other_element : other.data) {
        java.util.List<java.lang.String> __this__data_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__data.add(__this__data_copy);
      }
      this.data = __this__data;
    }
    if (other.isSetMasters()) {
      java.util.List<java.util.List<java.lang.String>> __this__masters = new java.util.ArrayList<java.util.List<java.lang.String>>(other.masters.size());
      for (java.util.List<java.lang.String> other_element : other.masters) {
        java.util.List<java.lang.String> __this__masters_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__masters.add(__this__masters_copy);
      }
      this.masters = __this__masters;
    }
    this.sys_status = other.sys_status;
  }

  public MasterCheckModel deepCopy() {
    return new MasterCheckModel(this);
  }

  @Override
  public void clear() {
    this.data = null;
    this.masters = null;
    setSys_statusIsSet(false);
    this.sys_status = 0;
  }

  public int getDataSize() {
    return (this.data == null) ? 0 : this.data.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getDataIterator() {
    return (this.data == null) ? null : this.data.iterator();
  }

  public void addToData(java.util.List<java.lang.String> elem) {
    if (this.data == null) {
      this.data = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.data.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getData() {
    return this.data;
  }

  public MasterCheckModel setData(java.util.List<java.util.List<java.lang.String>> data) {
    this.data = data;
    return this;
  }

  public void unsetData() {
    this.data = null;
  }

  /** Returns true if field data is set (has been assigned a value) and false otherwise */
  public boolean isSetData() {
    return this.data != null;
  }

  public void setDataIsSet(boolean value) {
    if (!value) {
      this.data = null;
    }
  }

  public int getMastersSize() {
    return (this.masters == null) ? 0 : this.masters.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getMastersIterator() {
    return (this.masters == null) ? null : this.masters.iterator();
  }

  public void addToMasters(java.util.List<java.lang.String> elem) {
    if (this.masters == null) {
      this.masters = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.masters.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getMasters() {
    return this.masters;
  }

  public MasterCheckModel setMasters(java.util.List<java.util.List<java.lang.String>> masters) {
    this.masters = masters;
    return this;
  }

  public void unsetMasters() {
    this.masters = null;
  }

  /** Returns true if field masters is set (has been assigned a value) and false otherwise */
  public boolean isSetMasters() {
    return this.masters != null;
  }

  public void setMastersIsSet(boolean value) {
    if (!value) {
      this.masters = null;
    }
  }

  public long getSys_status() {
    return this.sys_status;
  }

  public MasterCheckModel setSys_status(long sys_status) {
    this.sys_status = sys_status;
    setSys_statusIsSet(true);
    return this;
  }

  public void unsetSys_status() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SYS_STATUS_ISSET_ID);
  }

  /** Returns true if field sys_status is set (has been assigned a value) and false otherwise */
  public boolean isSetSys_status() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SYS_STATUS_ISSET_ID);
  }

  public void setSys_statusIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SYS_STATUS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case DATA:
      if (value == null) {
        unsetData();
      } else {
        setData((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case MASTERS:
      if (value == null) {
        unsetMasters();
      } else {
        setMasters((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case SYS_STATUS:
      if (value == null) {
        unsetSys_status();
      } else {
        setSys_status((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DATA:
      return getData();

    case MASTERS:
      return getMasters();

    case SYS_STATUS:
      return getSys_status();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DATA:
      return isSetData();
    case MASTERS:
      return isSetMasters();
    case SYS_STATUS:
      return isSetSys_status();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof MasterCheckModel)
      return this.equals((MasterCheckModel)that);
    return false;
  }

  public boolean equals(MasterCheckModel that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_data = true && this.isSetData();
    boolean that_present_data = true && that.isSetData();
    if (this_present_data || that_present_data) {
      if (!(this_present_data && that_present_data))
        return false;
      if (!this.data.equals(that.data))
        return false;
    }

    boolean this_present_masters = true && this.isSetMasters();
    boolean that_present_masters = true && that.isSetMasters();
    if (this_present_masters || that_present_masters) {
      if (!(this_present_masters && that_present_masters))
        return false;
      if (!this.masters.equals(that.masters))
        return false;
    }

    boolean this_present_sys_status = true;
    boolean that_present_sys_status = true;
    if (this_present_sys_status || that_present_sys_status) {
      if (!(this_present_sys_status && that_present_sys_status))
        return false;
      if (this.sys_status != that.sys_status)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetData()) ? 131071 : 524287);
    if (isSetData())
      hashCode = hashCode * 8191 + data.hashCode();

    hashCode = hashCode * 8191 + ((isSetMasters()) ? 131071 : 524287);
    if (isSetMasters())
      hashCode = hashCode * 8191 + masters.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(sys_status);

    return hashCode;
  }

  @Override
  public int compareTo(MasterCheckModel other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetData()).compareTo(other.isSetData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.data, other.data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMasters()).compareTo(other.isSetMasters());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMasters()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.masters, other.masters);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSys_status()).compareTo(other.isSetSys_status());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSys_status()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sys_status, other.sys_status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MasterCheckModel(");
    boolean first = true;

    sb.append("data:");
    if (this.data == null) {
      sb.append("null");
    } else {
      sb.append(this.data);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("masters:");
    if (this.masters == null) {
      sb.append("null");
    } else {
      sb.append(this.masters);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sys_status:");
    sb.append(this.sys_status);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MasterCheckModelStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MasterCheckModelStandardScheme getScheme() {
      return new MasterCheckModelStandardScheme();
    }
  }

  private static class MasterCheckModelStandardScheme extends org.apache.thrift.scheme.StandardScheme<MasterCheckModel> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MasterCheckModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.data = new java.util.ArrayList<java.util.List<java.lang.String>>(_list0.size);
                java.util.List<java.lang.String> _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  {
                    org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
                    _elem1 = new java.util.ArrayList<java.lang.String>(_list3.size);
                    java.lang.String _elem4;
                    for (int _i5 = 0; _i5 < _list3.size; ++_i5)
                    {
                      _elem4 = iprot.readString();
                      _elem1.add(_elem4);
                    }
                    iprot.readListEnd();
                  }
                  struct.data.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MASTERS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list6 = iprot.readListBegin();
                struct.masters = new java.util.ArrayList<java.util.List<java.lang.String>>(_list6.size);
                java.util.List<java.lang.String> _elem7;
                for (int _i8 = 0; _i8 < _list6.size; ++_i8)
                {
                  {
                    org.apache.thrift.protocol.TList _list9 = iprot.readListBegin();
                    _elem7 = new java.util.ArrayList<java.lang.String>(_list9.size);
                    java.lang.String _elem10;
                    for (int _i11 = 0; _i11 < _list9.size; ++_i11)
                    {
                      _elem10 = iprot.readString();
                      _elem7.add(_elem10);
                    }
                    iprot.readListEnd();
                  }
                  struct.masters.add(_elem7);
                }
                iprot.readListEnd();
              }
              struct.setMastersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SYS_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.sys_status = iprot.readI64();
              struct.setSys_statusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MasterCheckModel struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.data != null) {
        oprot.writeFieldBegin(DATA_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.data.size()));
          for (java.util.List<java.lang.String> _iter12 : struct.data)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter12.size()));
              for (java.lang.String _iter13 : _iter12)
              {
                oprot.writeString(_iter13);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.masters != null) {
        oprot.writeFieldBegin(MASTERS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.masters.size()));
          for (java.util.List<java.lang.String> _iter14 : struct.masters)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter14.size()));
              for (java.lang.String _iter15 : _iter14)
              {
                oprot.writeString(_iter15);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SYS_STATUS_FIELD_DESC);
      oprot.writeI64(struct.sys_status);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MasterCheckModelTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MasterCheckModelTupleScheme getScheme() {
      return new MasterCheckModelTupleScheme();
    }
  }

  private static class MasterCheckModelTupleScheme extends org.apache.thrift.scheme.TupleScheme<MasterCheckModel> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MasterCheckModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetData()) {
        optionals.set(0);
      }
      if (struct.isSetMasters()) {
        optionals.set(1);
      }
      if (struct.isSetSys_status()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetData()) {
        {
          oprot.writeI32(struct.data.size());
          for (java.util.List<java.lang.String> _iter16 : struct.data)
          {
            {
              oprot.writeI32(_iter16.size());
              for (java.lang.String _iter17 : _iter16)
              {
                oprot.writeString(_iter17);
              }
            }
          }
        }
      }
      if (struct.isSetMasters()) {
        {
          oprot.writeI32(struct.masters.size());
          for (java.util.List<java.lang.String> _iter18 : struct.masters)
          {
            {
              oprot.writeI32(_iter18.size());
              for (java.lang.String _iter19 : _iter18)
              {
                oprot.writeString(_iter19);
              }
            }
          }
        }
      }
      if (struct.isSetSys_status()) {
        oprot.writeI64(struct.sys_status);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MasterCheckModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list20 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.data = new java.util.ArrayList<java.util.List<java.lang.String>>(_list20.size);
          java.util.List<java.lang.String> _elem21;
          for (int _i22 = 0; _i22 < _list20.size; ++_i22)
          {
            {
              org.apache.thrift.protocol.TList _list23 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem21 = new java.util.ArrayList<java.lang.String>(_list23.size);
              java.lang.String _elem24;
              for (int _i25 = 0; _i25 < _list23.size; ++_i25)
              {
                _elem24 = iprot.readString();
                _elem21.add(_elem24);
              }
            }
            struct.data.add(_elem21);
          }
        }
        struct.setDataIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list26 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.masters = new java.util.ArrayList<java.util.List<java.lang.String>>(_list26.size);
          java.util.List<java.lang.String> _elem27;
          for (int _i28 = 0; _i28 < _list26.size; ++_i28)
          {
            {
              org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem27 = new java.util.ArrayList<java.lang.String>(_list29.size);
              java.lang.String _elem30;
              for (int _i31 = 0; _i31 < _list29.size; ++_i31)
              {
                _elem30 = iprot.readString();
                _elem27.add(_elem30);
              }
            }
            struct.masters.add(_elem27);
          }
        }
        struct.setMastersIsSet(true);
      }
      if (incoming.get(2)) {
        struct.sys_status = iprot.readI64();
        struct.setSys_statusIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

