/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package won;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-02-27")
public class RatingsModel implements org.apache.thrift.TBase<RatingsModel, RatingsModel._Fields>, java.io.Serializable, Cloneable, Comparable<RatingsModel> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RatingsModel");

  private static final org.apache.thrift.protocol.TField DG_RATING_FIELD_DESC = new org.apache.thrift.protocol.TField("dgRating", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField EPS_RATING_FIELD_DESC = new org.apache.thrift.protocol.TField("epsRating", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField RS_RATING_FIELD_DESC = new org.apache.thrift.protocol.TField("rsRating", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField ACC_DIS_FIELD_DESC = new org.apache.thrift.protocol.TField("accDis", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField GROUP_RANK_FIELD_DESC = new org.apache.thrift.protocol.TField("groupRank", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField MARKET_OUTLOOK_FIELD_DESC = new org.apache.thrift.protocol.TField("marketOutlook", org.apache.thrift.protocol.TType.LIST, (short)6);
  private static final org.apache.thrift.protocol.TField SYS_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("sys_status", org.apache.thrift.protocol.TType.I64, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RatingsModelStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RatingsModelTupleSchemeFactory();

  public java.util.List<java.util.List<java.lang.String>> dgRating; // required
  public java.util.List<java.util.List<java.lang.String>> epsRating; // required
  public java.util.List<java.util.List<java.lang.String>> rsRating; // required
  public java.util.List<java.util.List<java.lang.String>> accDis; // required
  public java.util.List<java.util.List<java.lang.String>> groupRank; // required
  public java.util.List<java.util.List<java.lang.String>> marketOutlook; // required
  public long sys_status; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DG_RATING((short)1, "dgRating"),
    EPS_RATING((short)2, "epsRating"),
    RS_RATING((short)3, "rsRating"),
    ACC_DIS((short)4, "accDis"),
    GROUP_RANK((short)5, "groupRank"),
    MARKET_OUTLOOK((short)6, "marketOutlook"),
    SYS_STATUS((short)7, "sys_status");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DG_RATING
          return DG_RATING;
        case 2: // EPS_RATING
          return EPS_RATING;
        case 3: // RS_RATING
          return RS_RATING;
        case 4: // ACC_DIS
          return ACC_DIS;
        case 5: // GROUP_RANK
          return GROUP_RANK;
        case 6: // MARKET_OUTLOOK
          return MARKET_OUTLOOK;
        case 7: // SYS_STATUS
          return SYS_STATUS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SYS_STATUS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DG_RATING, new org.apache.thrift.meta_data.FieldMetaData("dgRating", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.EPS_RATING, new org.apache.thrift.meta_data.FieldMetaData("epsRating", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.RS_RATING, new org.apache.thrift.meta_data.FieldMetaData("rsRating", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.ACC_DIS, new org.apache.thrift.meta_data.FieldMetaData("accDis", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.GROUP_RANK, new org.apache.thrift.meta_data.FieldMetaData("groupRank", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.MARKET_OUTLOOK, new org.apache.thrift.meta_data.FieldMetaData("marketOutlook", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.SYS_STATUS, new org.apache.thrift.meta_data.FieldMetaData("sys_status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RatingsModel.class, metaDataMap);
  }

  public RatingsModel() {
  }

  public RatingsModel(
    java.util.List<java.util.List<java.lang.String>> dgRating,
    java.util.List<java.util.List<java.lang.String>> epsRating,
    java.util.List<java.util.List<java.lang.String>> rsRating,
    java.util.List<java.util.List<java.lang.String>> accDis,
    java.util.List<java.util.List<java.lang.String>> groupRank,
    java.util.List<java.util.List<java.lang.String>> marketOutlook,
    long sys_status)
  {
    this();
    this.dgRating = dgRating;
    this.epsRating = epsRating;
    this.rsRating = rsRating;
    this.accDis = accDis;
    this.groupRank = groupRank;
    this.marketOutlook = marketOutlook;
    this.sys_status = sys_status;
    setSys_statusIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RatingsModel(RatingsModel other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDgRating()) {
      java.util.List<java.util.List<java.lang.String>> __this__dgRating = new java.util.ArrayList<java.util.List<java.lang.String>>(other.dgRating.size());
      for (java.util.List<java.lang.String> other_element : other.dgRating) {
        java.util.List<java.lang.String> __this__dgRating_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__dgRating.add(__this__dgRating_copy);
      }
      this.dgRating = __this__dgRating;
    }
    if (other.isSetEpsRating()) {
      java.util.List<java.util.List<java.lang.String>> __this__epsRating = new java.util.ArrayList<java.util.List<java.lang.String>>(other.epsRating.size());
      for (java.util.List<java.lang.String> other_element : other.epsRating) {
        java.util.List<java.lang.String> __this__epsRating_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__epsRating.add(__this__epsRating_copy);
      }
      this.epsRating = __this__epsRating;
    }
    if (other.isSetRsRating()) {
      java.util.List<java.util.List<java.lang.String>> __this__rsRating = new java.util.ArrayList<java.util.List<java.lang.String>>(other.rsRating.size());
      for (java.util.List<java.lang.String> other_element : other.rsRating) {
        java.util.List<java.lang.String> __this__rsRating_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__rsRating.add(__this__rsRating_copy);
      }
      this.rsRating = __this__rsRating;
    }
    if (other.isSetAccDis()) {
      java.util.List<java.util.List<java.lang.String>> __this__accDis = new java.util.ArrayList<java.util.List<java.lang.String>>(other.accDis.size());
      for (java.util.List<java.lang.String> other_element : other.accDis) {
        java.util.List<java.lang.String> __this__accDis_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__accDis.add(__this__accDis_copy);
      }
      this.accDis = __this__accDis;
    }
    if (other.isSetGroupRank()) {
      java.util.List<java.util.List<java.lang.String>> __this__groupRank = new java.util.ArrayList<java.util.List<java.lang.String>>(other.groupRank.size());
      for (java.util.List<java.lang.String> other_element : other.groupRank) {
        java.util.List<java.lang.String> __this__groupRank_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__groupRank.add(__this__groupRank_copy);
      }
      this.groupRank = __this__groupRank;
    }
    if (other.isSetMarketOutlook()) {
      java.util.List<java.util.List<java.lang.String>> __this__marketOutlook = new java.util.ArrayList<java.util.List<java.lang.String>>(other.marketOutlook.size());
      for (java.util.List<java.lang.String> other_element : other.marketOutlook) {
        java.util.List<java.lang.String> __this__marketOutlook_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__marketOutlook.add(__this__marketOutlook_copy);
      }
      this.marketOutlook = __this__marketOutlook;
    }
    this.sys_status = other.sys_status;
  }

  public RatingsModel deepCopy() {
    return new RatingsModel(this);
  }

  @Override
  public void clear() {
    this.dgRating = null;
    this.epsRating = null;
    this.rsRating = null;
    this.accDis = null;
    this.groupRank = null;
    this.marketOutlook = null;
    setSys_statusIsSet(false);
    this.sys_status = 0;
  }

  public int getDgRatingSize() {
    return (this.dgRating == null) ? 0 : this.dgRating.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getDgRatingIterator() {
    return (this.dgRating == null) ? null : this.dgRating.iterator();
  }

  public void addToDgRating(java.util.List<java.lang.String> elem) {
    if (this.dgRating == null) {
      this.dgRating = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.dgRating.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getDgRating() {
    return this.dgRating;
  }

  public RatingsModel setDgRating(java.util.List<java.util.List<java.lang.String>> dgRating) {
    this.dgRating = dgRating;
    return this;
  }

  public void unsetDgRating() {
    this.dgRating = null;
  }

  /** Returns true if field dgRating is set (has been assigned a value) and false otherwise */
  public boolean isSetDgRating() {
    return this.dgRating != null;
  }

  public void setDgRatingIsSet(boolean value) {
    if (!value) {
      this.dgRating = null;
    }
  }

  public int getEpsRatingSize() {
    return (this.epsRating == null) ? 0 : this.epsRating.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getEpsRatingIterator() {
    return (this.epsRating == null) ? null : this.epsRating.iterator();
  }

  public void addToEpsRating(java.util.List<java.lang.String> elem) {
    if (this.epsRating == null) {
      this.epsRating = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.epsRating.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getEpsRating() {
    return this.epsRating;
  }

  public RatingsModel setEpsRating(java.util.List<java.util.List<java.lang.String>> epsRating) {
    this.epsRating = epsRating;
    return this;
  }

  public void unsetEpsRating() {
    this.epsRating = null;
  }

  /** Returns true if field epsRating is set (has been assigned a value) and false otherwise */
  public boolean isSetEpsRating() {
    return this.epsRating != null;
  }

  public void setEpsRatingIsSet(boolean value) {
    if (!value) {
      this.epsRating = null;
    }
  }

  public int getRsRatingSize() {
    return (this.rsRating == null) ? 0 : this.rsRating.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getRsRatingIterator() {
    return (this.rsRating == null) ? null : this.rsRating.iterator();
  }

  public void addToRsRating(java.util.List<java.lang.String> elem) {
    if (this.rsRating == null) {
      this.rsRating = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.rsRating.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getRsRating() {
    return this.rsRating;
  }

  public RatingsModel setRsRating(java.util.List<java.util.List<java.lang.String>> rsRating) {
    this.rsRating = rsRating;
    return this;
  }

  public void unsetRsRating() {
    this.rsRating = null;
  }

  /** Returns true if field rsRating is set (has been assigned a value) and false otherwise */
  public boolean isSetRsRating() {
    return this.rsRating != null;
  }

  public void setRsRatingIsSet(boolean value) {
    if (!value) {
      this.rsRating = null;
    }
  }

  public int getAccDisSize() {
    return (this.accDis == null) ? 0 : this.accDis.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getAccDisIterator() {
    return (this.accDis == null) ? null : this.accDis.iterator();
  }

  public void addToAccDis(java.util.List<java.lang.String> elem) {
    if (this.accDis == null) {
      this.accDis = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.accDis.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getAccDis() {
    return this.accDis;
  }

  public RatingsModel setAccDis(java.util.List<java.util.List<java.lang.String>> accDis) {
    this.accDis = accDis;
    return this;
  }

  public void unsetAccDis() {
    this.accDis = null;
  }

  /** Returns true if field accDis is set (has been assigned a value) and false otherwise */
  public boolean isSetAccDis() {
    return this.accDis != null;
  }

  public void setAccDisIsSet(boolean value) {
    if (!value) {
      this.accDis = null;
    }
  }

  public int getGroupRankSize() {
    return (this.groupRank == null) ? 0 : this.groupRank.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getGroupRankIterator() {
    return (this.groupRank == null) ? null : this.groupRank.iterator();
  }

  public void addToGroupRank(java.util.List<java.lang.String> elem) {
    if (this.groupRank == null) {
      this.groupRank = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.groupRank.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getGroupRank() {
    return this.groupRank;
  }

  public RatingsModel setGroupRank(java.util.List<java.util.List<java.lang.String>> groupRank) {
    this.groupRank = groupRank;
    return this;
  }

  public void unsetGroupRank() {
    this.groupRank = null;
  }

  /** Returns true if field groupRank is set (has been assigned a value) and false otherwise */
  public boolean isSetGroupRank() {
    return this.groupRank != null;
  }

  public void setGroupRankIsSet(boolean value) {
    if (!value) {
      this.groupRank = null;
    }
  }

  public int getMarketOutlookSize() {
    return (this.marketOutlook == null) ? 0 : this.marketOutlook.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getMarketOutlookIterator() {
    return (this.marketOutlook == null) ? null : this.marketOutlook.iterator();
  }

  public void addToMarketOutlook(java.util.List<java.lang.String> elem) {
    if (this.marketOutlook == null) {
      this.marketOutlook = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.marketOutlook.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getMarketOutlook() {
    return this.marketOutlook;
  }

  public RatingsModel setMarketOutlook(java.util.List<java.util.List<java.lang.String>> marketOutlook) {
    this.marketOutlook = marketOutlook;
    return this;
  }

  public void unsetMarketOutlook() {
    this.marketOutlook = null;
  }

  /** Returns true if field marketOutlook is set (has been assigned a value) and false otherwise */
  public boolean isSetMarketOutlook() {
    return this.marketOutlook != null;
  }

  public void setMarketOutlookIsSet(boolean value) {
    if (!value) {
      this.marketOutlook = null;
    }
  }

  public long getSys_status() {
    return this.sys_status;
  }

  public RatingsModel setSys_status(long sys_status) {
    this.sys_status = sys_status;
    setSys_statusIsSet(true);
    return this;
  }

  public void unsetSys_status() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SYS_STATUS_ISSET_ID);
  }

  /** Returns true if field sys_status is set (has been assigned a value) and false otherwise */
  public boolean isSetSys_status() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SYS_STATUS_ISSET_ID);
  }

  public void setSys_statusIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SYS_STATUS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case DG_RATING:
      if (value == null) {
        unsetDgRating();
      } else {
        setDgRating((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case EPS_RATING:
      if (value == null) {
        unsetEpsRating();
      } else {
        setEpsRating((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case RS_RATING:
      if (value == null) {
        unsetRsRating();
      } else {
        setRsRating((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case ACC_DIS:
      if (value == null) {
        unsetAccDis();
      } else {
        setAccDis((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case GROUP_RANK:
      if (value == null) {
        unsetGroupRank();
      } else {
        setGroupRank((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case MARKET_OUTLOOK:
      if (value == null) {
        unsetMarketOutlook();
      } else {
        setMarketOutlook((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case SYS_STATUS:
      if (value == null) {
        unsetSys_status();
      } else {
        setSys_status((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DG_RATING:
      return getDgRating();

    case EPS_RATING:
      return getEpsRating();

    case RS_RATING:
      return getRsRating();

    case ACC_DIS:
      return getAccDis();

    case GROUP_RANK:
      return getGroupRank();

    case MARKET_OUTLOOK:
      return getMarketOutlook();

    case SYS_STATUS:
      return getSys_status();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DG_RATING:
      return isSetDgRating();
    case EPS_RATING:
      return isSetEpsRating();
    case RS_RATING:
      return isSetRsRating();
    case ACC_DIS:
      return isSetAccDis();
    case GROUP_RANK:
      return isSetGroupRank();
    case MARKET_OUTLOOK:
      return isSetMarketOutlook();
    case SYS_STATUS:
      return isSetSys_status();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RatingsModel)
      return this.equals((RatingsModel)that);
    return false;
  }

  public boolean equals(RatingsModel that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_dgRating = true && this.isSetDgRating();
    boolean that_present_dgRating = true && that.isSetDgRating();
    if (this_present_dgRating || that_present_dgRating) {
      if (!(this_present_dgRating && that_present_dgRating))
        return false;
      if (!this.dgRating.equals(that.dgRating))
        return false;
    }

    boolean this_present_epsRating = true && this.isSetEpsRating();
    boolean that_present_epsRating = true && that.isSetEpsRating();
    if (this_present_epsRating || that_present_epsRating) {
      if (!(this_present_epsRating && that_present_epsRating))
        return false;
      if (!this.epsRating.equals(that.epsRating))
        return false;
    }

    boolean this_present_rsRating = true && this.isSetRsRating();
    boolean that_present_rsRating = true && that.isSetRsRating();
    if (this_present_rsRating || that_present_rsRating) {
      if (!(this_present_rsRating && that_present_rsRating))
        return false;
      if (!this.rsRating.equals(that.rsRating))
        return false;
    }

    boolean this_present_accDis = true && this.isSetAccDis();
    boolean that_present_accDis = true && that.isSetAccDis();
    if (this_present_accDis || that_present_accDis) {
      if (!(this_present_accDis && that_present_accDis))
        return false;
      if (!this.accDis.equals(that.accDis))
        return false;
    }

    boolean this_present_groupRank = true && this.isSetGroupRank();
    boolean that_present_groupRank = true && that.isSetGroupRank();
    if (this_present_groupRank || that_present_groupRank) {
      if (!(this_present_groupRank && that_present_groupRank))
        return false;
      if (!this.groupRank.equals(that.groupRank))
        return false;
    }

    boolean this_present_marketOutlook = true && this.isSetMarketOutlook();
    boolean that_present_marketOutlook = true && that.isSetMarketOutlook();
    if (this_present_marketOutlook || that_present_marketOutlook) {
      if (!(this_present_marketOutlook && that_present_marketOutlook))
        return false;
      if (!this.marketOutlook.equals(that.marketOutlook))
        return false;
    }

    boolean this_present_sys_status = true;
    boolean that_present_sys_status = true;
    if (this_present_sys_status || that_present_sys_status) {
      if (!(this_present_sys_status && that_present_sys_status))
        return false;
      if (this.sys_status != that.sys_status)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDgRating()) ? 131071 : 524287);
    if (isSetDgRating())
      hashCode = hashCode * 8191 + dgRating.hashCode();

    hashCode = hashCode * 8191 + ((isSetEpsRating()) ? 131071 : 524287);
    if (isSetEpsRating())
      hashCode = hashCode * 8191 + epsRating.hashCode();

    hashCode = hashCode * 8191 + ((isSetRsRating()) ? 131071 : 524287);
    if (isSetRsRating())
      hashCode = hashCode * 8191 + rsRating.hashCode();

    hashCode = hashCode * 8191 + ((isSetAccDis()) ? 131071 : 524287);
    if (isSetAccDis())
      hashCode = hashCode * 8191 + accDis.hashCode();

    hashCode = hashCode * 8191 + ((isSetGroupRank()) ? 131071 : 524287);
    if (isSetGroupRank())
      hashCode = hashCode * 8191 + groupRank.hashCode();

    hashCode = hashCode * 8191 + ((isSetMarketOutlook()) ? 131071 : 524287);
    if (isSetMarketOutlook())
      hashCode = hashCode * 8191 + marketOutlook.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(sys_status);

    return hashCode;
  }

  @Override
  public int compareTo(RatingsModel other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDgRating()).compareTo(other.isSetDgRating());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDgRating()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dgRating, other.dgRating);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEpsRating()).compareTo(other.isSetEpsRating());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEpsRating()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.epsRating, other.epsRating);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRsRating()).compareTo(other.isSetRsRating());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRsRating()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rsRating, other.rsRating);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAccDis()).compareTo(other.isSetAccDis());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccDis()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accDis, other.accDis);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGroupRank()).compareTo(other.isSetGroupRank());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGroupRank()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.groupRank, other.groupRank);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMarketOutlook()).compareTo(other.isSetMarketOutlook());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMarketOutlook()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.marketOutlook, other.marketOutlook);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSys_status()).compareTo(other.isSetSys_status());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSys_status()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sys_status, other.sys_status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RatingsModel(");
    boolean first = true;

    sb.append("dgRating:");
    if (this.dgRating == null) {
      sb.append("null");
    } else {
      sb.append(this.dgRating);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("epsRating:");
    if (this.epsRating == null) {
      sb.append("null");
    } else {
      sb.append(this.epsRating);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rsRating:");
    if (this.rsRating == null) {
      sb.append("null");
    } else {
      sb.append(this.rsRating);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("accDis:");
    if (this.accDis == null) {
      sb.append("null");
    } else {
      sb.append(this.accDis);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("groupRank:");
    if (this.groupRank == null) {
      sb.append("null");
    } else {
      sb.append(this.groupRank);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("marketOutlook:");
    if (this.marketOutlook == null) {
      sb.append("null");
    } else {
      sb.append(this.marketOutlook);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sys_status:");
    sb.append(this.sys_status);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RatingsModelStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RatingsModelStandardScheme getScheme() {
      return new RatingsModelStandardScheme();
    }
  }

  private static class RatingsModelStandardScheme extends org.apache.thrift.scheme.StandardScheme<RatingsModel> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RatingsModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DG_RATING
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list32 = iprot.readListBegin();
                struct.dgRating = new java.util.ArrayList<java.util.List<java.lang.String>>(_list32.size);
                java.util.List<java.lang.String> _elem33;
                for (int _i34 = 0; _i34 < _list32.size; ++_i34)
                {
                  {
                    org.apache.thrift.protocol.TList _list35 = iprot.readListBegin();
                    _elem33 = new java.util.ArrayList<java.lang.String>(_list35.size);
                    java.lang.String _elem36;
                    for (int _i37 = 0; _i37 < _list35.size; ++_i37)
                    {
                      _elem36 = iprot.readString();
                      _elem33.add(_elem36);
                    }
                    iprot.readListEnd();
                  }
                  struct.dgRating.add(_elem33);
                }
                iprot.readListEnd();
              }
              struct.setDgRatingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EPS_RATING
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list38 = iprot.readListBegin();
                struct.epsRating = new java.util.ArrayList<java.util.List<java.lang.String>>(_list38.size);
                java.util.List<java.lang.String> _elem39;
                for (int _i40 = 0; _i40 < _list38.size; ++_i40)
                {
                  {
                    org.apache.thrift.protocol.TList _list41 = iprot.readListBegin();
                    _elem39 = new java.util.ArrayList<java.lang.String>(_list41.size);
                    java.lang.String _elem42;
                    for (int _i43 = 0; _i43 < _list41.size; ++_i43)
                    {
                      _elem42 = iprot.readString();
                      _elem39.add(_elem42);
                    }
                    iprot.readListEnd();
                  }
                  struct.epsRating.add(_elem39);
                }
                iprot.readListEnd();
              }
              struct.setEpsRatingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RS_RATING
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list44 = iprot.readListBegin();
                struct.rsRating = new java.util.ArrayList<java.util.List<java.lang.String>>(_list44.size);
                java.util.List<java.lang.String> _elem45;
                for (int _i46 = 0; _i46 < _list44.size; ++_i46)
                {
                  {
                    org.apache.thrift.protocol.TList _list47 = iprot.readListBegin();
                    _elem45 = new java.util.ArrayList<java.lang.String>(_list47.size);
                    java.lang.String _elem48;
                    for (int _i49 = 0; _i49 < _list47.size; ++_i49)
                    {
                      _elem48 = iprot.readString();
                      _elem45.add(_elem48);
                    }
                    iprot.readListEnd();
                  }
                  struct.rsRating.add(_elem45);
                }
                iprot.readListEnd();
              }
              struct.setRsRatingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ACC_DIS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list50 = iprot.readListBegin();
                struct.accDis = new java.util.ArrayList<java.util.List<java.lang.String>>(_list50.size);
                java.util.List<java.lang.String> _elem51;
                for (int _i52 = 0; _i52 < _list50.size; ++_i52)
                {
                  {
                    org.apache.thrift.protocol.TList _list53 = iprot.readListBegin();
                    _elem51 = new java.util.ArrayList<java.lang.String>(_list53.size);
                    java.lang.String _elem54;
                    for (int _i55 = 0; _i55 < _list53.size; ++_i55)
                    {
                      _elem54 = iprot.readString();
                      _elem51.add(_elem54);
                    }
                    iprot.readListEnd();
                  }
                  struct.accDis.add(_elem51);
                }
                iprot.readListEnd();
              }
              struct.setAccDisIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // GROUP_RANK
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list56 = iprot.readListBegin();
                struct.groupRank = new java.util.ArrayList<java.util.List<java.lang.String>>(_list56.size);
                java.util.List<java.lang.String> _elem57;
                for (int _i58 = 0; _i58 < _list56.size; ++_i58)
                {
                  {
                    org.apache.thrift.protocol.TList _list59 = iprot.readListBegin();
                    _elem57 = new java.util.ArrayList<java.lang.String>(_list59.size);
                    java.lang.String _elem60;
                    for (int _i61 = 0; _i61 < _list59.size; ++_i61)
                    {
                      _elem60 = iprot.readString();
                      _elem57.add(_elem60);
                    }
                    iprot.readListEnd();
                  }
                  struct.groupRank.add(_elem57);
                }
                iprot.readListEnd();
              }
              struct.setGroupRankIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // MARKET_OUTLOOK
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list62 = iprot.readListBegin();
                struct.marketOutlook = new java.util.ArrayList<java.util.List<java.lang.String>>(_list62.size);
                java.util.List<java.lang.String> _elem63;
                for (int _i64 = 0; _i64 < _list62.size; ++_i64)
                {
                  {
                    org.apache.thrift.protocol.TList _list65 = iprot.readListBegin();
                    _elem63 = new java.util.ArrayList<java.lang.String>(_list65.size);
                    java.lang.String _elem66;
                    for (int _i67 = 0; _i67 < _list65.size; ++_i67)
                    {
                      _elem66 = iprot.readString();
                      _elem63.add(_elem66);
                    }
                    iprot.readListEnd();
                  }
                  struct.marketOutlook.add(_elem63);
                }
                iprot.readListEnd();
              }
              struct.setMarketOutlookIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // SYS_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.sys_status = iprot.readI64();
              struct.setSys_statusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RatingsModel struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dgRating != null) {
        oprot.writeFieldBegin(DG_RATING_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.dgRating.size()));
          for (java.util.List<java.lang.String> _iter68 : struct.dgRating)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter68.size()));
              for (java.lang.String _iter69 : _iter68)
              {
                oprot.writeString(_iter69);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.epsRating != null) {
        oprot.writeFieldBegin(EPS_RATING_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.epsRating.size()));
          for (java.util.List<java.lang.String> _iter70 : struct.epsRating)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter70.size()));
              for (java.lang.String _iter71 : _iter70)
              {
                oprot.writeString(_iter71);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.rsRating != null) {
        oprot.writeFieldBegin(RS_RATING_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.rsRating.size()));
          for (java.util.List<java.lang.String> _iter72 : struct.rsRating)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter72.size()));
              for (java.lang.String _iter73 : _iter72)
              {
                oprot.writeString(_iter73);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.accDis != null) {
        oprot.writeFieldBegin(ACC_DIS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.accDis.size()));
          for (java.util.List<java.lang.String> _iter74 : struct.accDis)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter74.size()));
              for (java.lang.String _iter75 : _iter74)
              {
                oprot.writeString(_iter75);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.groupRank != null) {
        oprot.writeFieldBegin(GROUP_RANK_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.groupRank.size()));
          for (java.util.List<java.lang.String> _iter76 : struct.groupRank)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter76.size()));
              for (java.lang.String _iter77 : _iter76)
              {
                oprot.writeString(_iter77);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.marketOutlook != null) {
        oprot.writeFieldBegin(MARKET_OUTLOOK_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.marketOutlook.size()));
          for (java.util.List<java.lang.String> _iter78 : struct.marketOutlook)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter78.size()));
              for (java.lang.String _iter79 : _iter78)
              {
                oprot.writeString(_iter79);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SYS_STATUS_FIELD_DESC);
      oprot.writeI64(struct.sys_status);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RatingsModelTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RatingsModelTupleScheme getScheme() {
      return new RatingsModelTupleScheme();
    }
  }

  private static class RatingsModelTupleScheme extends org.apache.thrift.scheme.TupleScheme<RatingsModel> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RatingsModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDgRating()) {
        optionals.set(0);
      }
      if (struct.isSetEpsRating()) {
        optionals.set(1);
      }
      if (struct.isSetRsRating()) {
        optionals.set(2);
      }
      if (struct.isSetAccDis()) {
        optionals.set(3);
      }
      if (struct.isSetGroupRank()) {
        optionals.set(4);
      }
      if (struct.isSetMarketOutlook()) {
        optionals.set(5);
      }
      if (struct.isSetSys_status()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetDgRating()) {
        {
          oprot.writeI32(struct.dgRating.size());
          for (java.util.List<java.lang.String> _iter80 : struct.dgRating)
          {
            {
              oprot.writeI32(_iter80.size());
              for (java.lang.String _iter81 : _iter80)
              {
                oprot.writeString(_iter81);
              }
            }
          }
        }
      }
      if (struct.isSetEpsRating()) {
        {
          oprot.writeI32(struct.epsRating.size());
          for (java.util.List<java.lang.String> _iter82 : struct.epsRating)
          {
            {
              oprot.writeI32(_iter82.size());
              for (java.lang.String _iter83 : _iter82)
              {
                oprot.writeString(_iter83);
              }
            }
          }
        }
      }
      if (struct.isSetRsRating()) {
        {
          oprot.writeI32(struct.rsRating.size());
          for (java.util.List<java.lang.String> _iter84 : struct.rsRating)
          {
            {
              oprot.writeI32(_iter84.size());
              for (java.lang.String _iter85 : _iter84)
              {
                oprot.writeString(_iter85);
              }
            }
          }
        }
      }
      if (struct.isSetAccDis()) {
        {
          oprot.writeI32(struct.accDis.size());
          for (java.util.List<java.lang.String> _iter86 : struct.accDis)
          {
            {
              oprot.writeI32(_iter86.size());
              for (java.lang.String _iter87 : _iter86)
              {
                oprot.writeString(_iter87);
              }
            }
          }
        }
      }
      if (struct.isSetGroupRank()) {
        {
          oprot.writeI32(struct.groupRank.size());
          for (java.util.List<java.lang.String> _iter88 : struct.groupRank)
          {
            {
              oprot.writeI32(_iter88.size());
              for (java.lang.String _iter89 : _iter88)
              {
                oprot.writeString(_iter89);
              }
            }
          }
        }
      }
      if (struct.isSetMarketOutlook()) {
        {
          oprot.writeI32(struct.marketOutlook.size());
          for (java.util.List<java.lang.String> _iter90 : struct.marketOutlook)
          {
            {
              oprot.writeI32(_iter90.size());
              for (java.lang.String _iter91 : _iter90)
              {
                oprot.writeString(_iter91);
              }
            }
          }
        }
      }
      if (struct.isSetSys_status()) {
        oprot.writeI64(struct.sys_status);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RatingsModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list92 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.dgRating = new java.util.ArrayList<java.util.List<java.lang.String>>(_list92.size);
          java.util.List<java.lang.String> _elem93;
          for (int _i94 = 0; _i94 < _list92.size; ++_i94)
          {
            {
              org.apache.thrift.protocol.TList _list95 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem93 = new java.util.ArrayList<java.lang.String>(_list95.size);
              java.lang.String _elem96;
              for (int _i97 = 0; _i97 < _list95.size; ++_i97)
              {
                _elem96 = iprot.readString();
                _elem93.add(_elem96);
              }
            }
            struct.dgRating.add(_elem93);
          }
        }
        struct.setDgRatingIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list98 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.epsRating = new java.util.ArrayList<java.util.List<java.lang.String>>(_list98.size);
          java.util.List<java.lang.String> _elem99;
          for (int _i100 = 0; _i100 < _list98.size; ++_i100)
          {
            {
              org.apache.thrift.protocol.TList _list101 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem99 = new java.util.ArrayList<java.lang.String>(_list101.size);
              java.lang.String _elem102;
              for (int _i103 = 0; _i103 < _list101.size; ++_i103)
              {
                _elem102 = iprot.readString();
                _elem99.add(_elem102);
              }
            }
            struct.epsRating.add(_elem99);
          }
        }
        struct.setEpsRatingIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list104 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.rsRating = new java.util.ArrayList<java.util.List<java.lang.String>>(_list104.size);
          java.util.List<java.lang.String> _elem105;
          for (int _i106 = 0; _i106 < _list104.size; ++_i106)
          {
            {
              org.apache.thrift.protocol.TList _list107 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem105 = new java.util.ArrayList<java.lang.String>(_list107.size);
              java.lang.String _elem108;
              for (int _i109 = 0; _i109 < _list107.size; ++_i109)
              {
                _elem108 = iprot.readString();
                _elem105.add(_elem108);
              }
            }
            struct.rsRating.add(_elem105);
          }
        }
        struct.setRsRatingIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list110 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.accDis = new java.util.ArrayList<java.util.List<java.lang.String>>(_list110.size);
          java.util.List<java.lang.String> _elem111;
          for (int _i112 = 0; _i112 < _list110.size; ++_i112)
          {
            {
              org.apache.thrift.protocol.TList _list113 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem111 = new java.util.ArrayList<java.lang.String>(_list113.size);
              java.lang.String _elem114;
              for (int _i115 = 0; _i115 < _list113.size; ++_i115)
              {
                _elem114 = iprot.readString();
                _elem111.add(_elem114);
              }
            }
            struct.accDis.add(_elem111);
          }
        }
        struct.setAccDisIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list116 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.groupRank = new java.util.ArrayList<java.util.List<java.lang.String>>(_list116.size);
          java.util.List<java.lang.String> _elem117;
          for (int _i118 = 0; _i118 < _list116.size; ++_i118)
          {
            {
              org.apache.thrift.protocol.TList _list119 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem117 = new java.util.ArrayList<java.lang.String>(_list119.size);
              java.lang.String _elem120;
              for (int _i121 = 0; _i121 < _list119.size; ++_i121)
              {
                _elem120 = iprot.readString();
                _elem117.add(_elem120);
              }
            }
            struct.groupRank.add(_elem117);
          }
        }
        struct.setGroupRankIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list122 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.marketOutlook = new java.util.ArrayList<java.util.List<java.lang.String>>(_list122.size);
          java.util.List<java.lang.String> _elem123;
          for (int _i124 = 0; _i124 < _list122.size; ++_i124)
          {
            {
              org.apache.thrift.protocol.TList _list125 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem123 = new java.util.ArrayList<java.lang.String>(_list125.size);
              java.lang.String _elem126;
              for (int _i127 = 0; _i127 < _list125.size; ++_i127)
              {
                _elem126 = iprot.readString();
                _elem123.add(_elem126);
              }
            }
            struct.marketOutlook.add(_elem123);
          }
        }
        struct.setMarketOutlookIsSet(true);
      }
      if (incoming.get(6)) {
        struct.sys_status = iprot.readI64();
        struct.setSys_statusIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

