/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package won;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-02-27")
public class Top33Model implements org.apache.thrift.TBase<Top33Model, Top33Model._Fields>, java.io.Serializable, Cloneable, Comparable<Top33Model> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Top33Model");

  private static final org.apache.thrift.protocol.TField DESCRIPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("description", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("data", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField RECENT_ADDITIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("recentAdditions", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField RECENT_REMOVALS_FIELD_DESC = new org.apache.thrift.protocol.TField("recentRemovals", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField SYS_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("sys_status", org.apache.thrift.protocol.TType.I64, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new Top33ModelStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new Top33ModelTupleSchemeFactory();

  public java.lang.String description; // required
  public java.util.List<java.util.List<java.lang.String>> data; // required
  public java.util.List<java.util.List<java.lang.String>> recentAdditions; // required
  public java.util.List<java.util.List<java.lang.String>> recentRemovals; // required
  public long sys_status; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DESCRIPTION((short)1, "description"),
    DATA((short)2, "data"),
    RECENT_ADDITIONS((short)3, "recentAdditions"),
    RECENT_REMOVALS((short)4, "recentRemovals"),
    SYS_STATUS((short)5, "sys_status");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DESCRIPTION
          return DESCRIPTION;
        case 2: // DATA
          return DATA;
        case 3: // RECENT_ADDITIONS
          return RECENT_ADDITIONS;
        case 4: // RECENT_REMOVALS
          return RECENT_REMOVALS;
        case 5: // SYS_STATUS
          return SYS_STATUS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SYS_STATUS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DESCRIPTION, new org.apache.thrift.meta_data.FieldMetaData("description", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DATA, new org.apache.thrift.meta_data.FieldMetaData("data", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.RECENT_ADDITIONS, new org.apache.thrift.meta_data.FieldMetaData("recentAdditions", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.RECENT_REMOVALS, new org.apache.thrift.meta_data.FieldMetaData("recentRemovals", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    tmpMap.put(_Fields.SYS_STATUS, new org.apache.thrift.meta_data.FieldMetaData("sys_status", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Top33Model.class, metaDataMap);
  }

  public Top33Model() {
  }

  public Top33Model(
    java.lang.String description,
    java.util.List<java.util.List<java.lang.String>> data,
    java.util.List<java.util.List<java.lang.String>> recentAdditions,
    java.util.List<java.util.List<java.lang.String>> recentRemovals,
    long sys_status)
  {
    this();
    this.description = description;
    this.data = data;
    this.recentAdditions = recentAdditions;
    this.recentRemovals = recentRemovals;
    this.sys_status = sys_status;
    setSys_statusIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Top33Model(Top33Model other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDescription()) {
      this.description = other.description;
    }
    if (other.isSetData()) {
      java.util.List<java.util.List<java.lang.String>> __this__data = new java.util.ArrayList<java.util.List<java.lang.String>>(other.data.size());
      for (java.util.List<java.lang.String> other_element : other.data) {
        java.util.List<java.lang.String> __this__data_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__data.add(__this__data_copy);
      }
      this.data = __this__data;
    }
    if (other.isSetRecentAdditions()) {
      java.util.List<java.util.List<java.lang.String>> __this__recentAdditions = new java.util.ArrayList<java.util.List<java.lang.String>>(other.recentAdditions.size());
      for (java.util.List<java.lang.String> other_element : other.recentAdditions) {
        java.util.List<java.lang.String> __this__recentAdditions_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__recentAdditions.add(__this__recentAdditions_copy);
      }
      this.recentAdditions = __this__recentAdditions;
    }
    if (other.isSetRecentRemovals()) {
      java.util.List<java.util.List<java.lang.String>> __this__recentRemovals = new java.util.ArrayList<java.util.List<java.lang.String>>(other.recentRemovals.size());
      for (java.util.List<java.lang.String> other_element : other.recentRemovals) {
        java.util.List<java.lang.String> __this__recentRemovals_copy = new java.util.ArrayList<java.lang.String>(other_element);
        __this__recentRemovals.add(__this__recentRemovals_copy);
      }
      this.recentRemovals = __this__recentRemovals;
    }
    this.sys_status = other.sys_status;
  }

  public Top33Model deepCopy() {
    return new Top33Model(this);
  }

  @Override
  public void clear() {
    this.description = null;
    this.data = null;
    this.recentAdditions = null;
    this.recentRemovals = null;
    setSys_statusIsSet(false);
    this.sys_status = 0;
  }

  public java.lang.String getDescription() {
    return this.description;
  }

  public Top33Model setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  public void unsetDescription() {
    this.description = null;
  }

  /** Returns true if field description is set (has been assigned a value) and false otherwise */
  public boolean isSetDescription() {
    return this.description != null;
  }

  public void setDescriptionIsSet(boolean value) {
    if (!value) {
      this.description = null;
    }
  }

  public int getDataSize() {
    return (this.data == null) ? 0 : this.data.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getDataIterator() {
    return (this.data == null) ? null : this.data.iterator();
  }

  public void addToData(java.util.List<java.lang.String> elem) {
    if (this.data == null) {
      this.data = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.data.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getData() {
    return this.data;
  }

  public Top33Model setData(java.util.List<java.util.List<java.lang.String>> data) {
    this.data = data;
    return this;
  }

  public void unsetData() {
    this.data = null;
  }

  /** Returns true if field data is set (has been assigned a value) and false otherwise */
  public boolean isSetData() {
    return this.data != null;
  }

  public void setDataIsSet(boolean value) {
    if (!value) {
      this.data = null;
    }
  }

  public int getRecentAdditionsSize() {
    return (this.recentAdditions == null) ? 0 : this.recentAdditions.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getRecentAdditionsIterator() {
    return (this.recentAdditions == null) ? null : this.recentAdditions.iterator();
  }

  public void addToRecentAdditions(java.util.List<java.lang.String> elem) {
    if (this.recentAdditions == null) {
      this.recentAdditions = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.recentAdditions.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getRecentAdditions() {
    return this.recentAdditions;
  }

  public Top33Model setRecentAdditions(java.util.List<java.util.List<java.lang.String>> recentAdditions) {
    this.recentAdditions = recentAdditions;
    return this;
  }

  public void unsetRecentAdditions() {
    this.recentAdditions = null;
  }

  /** Returns true if field recentAdditions is set (has been assigned a value) and false otherwise */
  public boolean isSetRecentAdditions() {
    return this.recentAdditions != null;
  }

  public void setRecentAdditionsIsSet(boolean value) {
    if (!value) {
      this.recentAdditions = null;
    }
  }

  public int getRecentRemovalsSize() {
    return (this.recentRemovals == null) ? 0 : this.recentRemovals.size();
  }

  public java.util.Iterator<java.util.List<java.lang.String>> getRecentRemovalsIterator() {
    return (this.recentRemovals == null) ? null : this.recentRemovals.iterator();
  }

  public void addToRecentRemovals(java.util.List<java.lang.String> elem) {
    if (this.recentRemovals == null) {
      this.recentRemovals = new java.util.ArrayList<java.util.List<java.lang.String>>();
    }
    this.recentRemovals.add(elem);
  }

  public java.util.List<java.util.List<java.lang.String>> getRecentRemovals() {
    return this.recentRemovals;
  }

  public Top33Model setRecentRemovals(java.util.List<java.util.List<java.lang.String>> recentRemovals) {
    this.recentRemovals = recentRemovals;
    return this;
  }

  public void unsetRecentRemovals() {
    this.recentRemovals = null;
  }

  /** Returns true if field recentRemovals is set (has been assigned a value) and false otherwise */
  public boolean isSetRecentRemovals() {
    return this.recentRemovals != null;
  }

  public void setRecentRemovalsIsSet(boolean value) {
    if (!value) {
      this.recentRemovals = null;
    }
  }

  public long getSys_status() {
    return this.sys_status;
  }

  public Top33Model setSys_status(long sys_status) {
    this.sys_status = sys_status;
    setSys_statusIsSet(true);
    return this;
  }

  public void unsetSys_status() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SYS_STATUS_ISSET_ID);
  }

  /** Returns true if field sys_status is set (has been assigned a value) and false otherwise */
  public boolean isSetSys_status() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SYS_STATUS_ISSET_ID);
  }

  public void setSys_statusIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SYS_STATUS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case DESCRIPTION:
      if (value == null) {
        unsetDescription();
      } else {
        setDescription((java.lang.String)value);
      }
      break;

    case DATA:
      if (value == null) {
        unsetData();
      } else {
        setData((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case RECENT_ADDITIONS:
      if (value == null) {
        unsetRecentAdditions();
      } else {
        setRecentAdditions((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case RECENT_REMOVALS:
      if (value == null) {
        unsetRecentRemovals();
      } else {
        setRecentRemovals((java.util.List<java.util.List<java.lang.String>>)value);
      }
      break;

    case SYS_STATUS:
      if (value == null) {
        unsetSys_status();
      } else {
        setSys_status((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DESCRIPTION:
      return getDescription();

    case DATA:
      return getData();

    case RECENT_ADDITIONS:
      return getRecentAdditions();

    case RECENT_REMOVALS:
      return getRecentRemovals();

    case SYS_STATUS:
      return getSys_status();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DESCRIPTION:
      return isSetDescription();
    case DATA:
      return isSetData();
    case RECENT_ADDITIONS:
      return isSetRecentAdditions();
    case RECENT_REMOVALS:
      return isSetRecentRemovals();
    case SYS_STATUS:
      return isSetSys_status();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Top33Model)
      return this.equals((Top33Model)that);
    return false;
  }

  public boolean equals(Top33Model that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_description = true && this.isSetDescription();
    boolean that_present_description = true && that.isSetDescription();
    if (this_present_description || that_present_description) {
      if (!(this_present_description && that_present_description))
        return false;
      if (!this.description.equals(that.description))
        return false;
    }

    boolean this_present_data = true && this.isSetData();
    boolean that_present_data = true && that.isSetData();
    if (this_present_data || that_present_data) {
      if (!(this_present_data && that_present_data))
        return false;
      if (!this.data.equals(that.data))
        return false;
    }

    boolean this_present_recentAdditions = true && this.isSetRecentAdditions();
    boolean that_present_recentAdditions = true && that.isSetRecentAdditions();
    if (this_present_recentAdditions || that_present_recentAdditions) {
      if (!(this_present_recentAdditions && that_present_recentAdditions))
        return false;
      if (!this.recentAdditions.equals(that.recentAdditions))
        return false;
    }

    boolean this_present_recentRemovals = true && this.isSetRecentRemovals();
    boolean that_present_recentRemovals = true && that.isSetRecentRemovals();
    if (this_present_recentRemovals || that_present_recentRemovals) {
      if (!(this_present_recentRemovals && that_present_recentRemovals))
        return false;
      if (!this.recentRemovals.equals(that.recentRemovals))
        return false;
    }

    boolean this_present_sys_status = true;
    boolean that_present_sys_status = true;
    if (this_present_sys_status || that_present_sys_status) {
      if (!(this_present_sys_status && that_present_sys_status))
        return false;
      if (this.sys_status != that.sys_status)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDescription()) ? 131071 : 524287);
    if (isSetDescription())
      hashCode = hashCode * 8191 + description.hashCode();

    hashCode = hashCode * 8191 + ((isSetData()) ? 131071 : 524287);
    if (isSetData())
      hashCode = hashCode * 8191 + data.hashCode();

    hashCode = hashCode * 8191 + ((isSetRecentAdditions()) ? 131071 : 524287);
    if (isSetRecentAdditions())
      hashCode = hashCode * 8191 + recentAdditions.hashCode();

    hashCode = hashCode * 8191 + ((isSetRecentRemovals()) ? 131071 : 524287);
    if (isSetRecentRemovals())
      hashCode = hashCode * 8191 + recentRemovals.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(sys_status);

    return hashCode;
  }

  @Override
  public int compareTo(Top33Model other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDescription()).compareTo(other.isSetDescription());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDescription()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.description, other.description);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetData()).compareTo(other.isSetData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.data, other.data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRecentAdditions()).compareTo(other.isSetRecentAdditions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRecentAdditions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.recentAdditions, other.recentAdditions);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRecentRemovals()).compareTo(other.isSetRecentRemovals());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRecentRemovals()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.recentRemovals, other.recentRemovals);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSys_status()).compareTo(other.isSetSys_status());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSys_status()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sys_status, other.sys_status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Top33Model(");
    boolean first = true;

    sb.append("description:");
    if (this.description == null) {
      sb.append("null");
    } else {
      sb.append(this.description);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("data:");
    if (this.data == null) {
      sb.append("null");
    } else {
      sb.append(this.data);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("recentAdditions:");
    if (this.recentAdditions == null) {
      sb.append("null");
    } else {
      sb.append(this.recentAdditions);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("recentRemovals:");
    if (this.recentRemovals == null) {
      sb.append("null");
    } else {
      sb.append(this.recentRemovals);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sys_status:");
    sb.append(this.sys_status);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class Top33ModelStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public Top33ModelStandardScheme getScheme() {
      return new Top33ModelStandardScheme();
    }
  }

  private static class Top33ModelStandardScheme extends org.apache.thrift.scheme.StandardScheme<Top33Model> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Top33Model struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DESCRIPTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.description = iprot.readString();
              struct.setDescriptionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list128 = iprot.readListBegin();
                struct.data = new java.util.ArrayList<java.util.List<java.lang.String>>(_list128.size);
                java.util.List<java.lang.String> _elem129;
                for (int _i130 = 0; _i130 < _list128.size; ++_i130)
                {
                  {
                    org.apache.thrift.protocol.TList _list131 = iprot.readListBegin();
                    _elem129 = new java.util.ArrayList<java.lang.String>(_list131.size);
                    java.lang.String _elem132;
                    for (int _i133 = 0; _i133 < _list131.size; ++_i133)
                    {
                      _elem132 = iprot.readString();
                      _elem129.add(_elem132);
                    }
                    iprot.readListEnd();
                  }
                  struct.data.add(_elem129);
                }
                iprot.readListEnd();
              }
              struct.setDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RECENT_ADDITIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list134 = iprot.readListBegin();
                struct.recentAdditions = new java.util.ArrayList<java.util.List<java.lang.String>>(_list134.size);
                java.util.List<java.lang.String> _elem135;
                for (int _i136 = 0; _i136 < _list134.size; ++_i136)
                {
                  {
                    org.apache.thrift.protocol.TList _list137 = iprot.readListBegin();
                    _elem135 = new java.util.ArrayList<java.lang.String>(_list137.size);
                    java.lang.String _elem138;
                    for (int _i139 = 0; _i139 < _list137.size; ++_i139)
                    {
                      _elem138 = iprot.readString();
                      _elem135.add(_elem138);
                    }
                    iprot.readListEnd();
                  }
                  struct.recentAdditions.add(_elem135);
                }
                iprot.readListEnd();
              }
              struct.setRecentAdditionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // RECENT_REMOVALS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list140 = iprot.readListBegin();
                struct.recentRemovals = new java.util.ArrayList<java.util.List<java.lang.String>>(_list140.size);
                java.util.List<java.lang.String> _elem141;
                for (int _i142 = 0; _i142 < _list140.size; ++_i142)
                {
                  {
                    org.apache.thrift.protocol.TList _list143 = iprot.readListBegin();
                    _elem141 = new java.util.ArrayList<java.lang.String>(_list143.size);
                    java.lang.String _elem144;
                    for (int _i145 = 0; _i145 < _list143.size; ++_i145)
                    {
                      _elem144 = iprot.readString();
                      _elem141.add(_elem144);
                    }
                    iprot.readListEnd();
                  }
                  struct.recentRemovals.add(_elem141);
                }
                iprot.readListEnd();
              }
              struct.setRecentRemovalsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SYS_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.sys_status = iprot.readI64();
              struct.setSys_statusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Top33Model struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.description != null) {
        oprot.writeFieldBegin(DESCRIPTION_FIELD_DESC);
        oprot.writeString(struct.description);
        oprot.writeFieldEnd();
      }
      if (struct.data != null) {
        oprot.writeFieldBegin(DATA_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.data.size()));
          for (java.util.List<java.lang.String> _iter146 : struct.data)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter146.size()));
              for (java.lang.String _iter147 : _iter146)
              {
                oprot.writeString(_iter147);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.recentAdditions != null) {
        oprot.writeFieldBegin(RECENT_ADDITIONS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.recentAdditions.size()));
          for (java.util.List<java.lang.String> _iter148 : struct.recentAdditions)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter148.size()));
              for (java.lang.String _iter149 : _iter148)
              {
                oprot.writeString(_iter149);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.recentRemovals != null) {
        oprot.writeFieldBegin(RECENT_REMOVALS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.recentRemovals.size()));
          for (java.util.List<java.lang.String> _iter150 : struct.recentRemovals)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter150.size()));
              for (java.lang.String _iter151 : _iter150)
              {
                oprot.writeString(_iter151);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SYS_STATUS_FIELD_DESC);
      oprot.writeI64(struct.sys_status);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class Top33ModelTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public Top33ModelTupleScheme getScheme() {
      return new Top33ModelTupleScheme();
    }
  }

  private static class Top33ModelTupleScheme extends org.apache.thrift.scheme.TupleScheme<Top33Model> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Top33Model struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDescription()) {
        optionals.set(0);
      }
      if (struct.isSetData()) {
        optionals.set(1);
      }
      if (struct.isSetRecentAdditions()) {
        optionals.set(2);
      }
      if (struct.isSetRecentRemovals()) {
        optionals.set(3);
      }
      if (struct.isSetSys_status()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetDescription()) {
        oprot.writeString(struct.description);
      }
      if (struct.isSetData()) {
        {
          oprot.writeI32(struct.data.size());
          for (java.util.List<java.lang.String> _iter152 : struct.data)
          {
            {
              oprot.writeI32(_iter152.size());
              for (java.lang.String _iter153 : _iter152)
              {
                oprot.writeString(_iter153);
              }
            }
          }
        }
      }
      if (struct.isSetRecentAdditions()) {
        {
          oprot.writeI32(struct.recentAdditions.size());
          for (java.util.List<java.lang.String> _iter154 : struct.recentAdditions)
          {
            {
              oprot.writeI32(_iter154.size());
              for (java.lang.String _iter155 : _iter154)
              {
                oprot.writeString(_iter155);
              }
            }
          }
        }
      }
      if (struct.isSetRecentRemovals()) {
        {
          oprot.writeI32(struct.recentRemovals.size());
          for (java.util.List<java.lang.String> _iter156 : struct.recentRemovals)
          {
            {
              oprot.writeI32(_iter156.size());
              for (java.lang.String _iter157 : _iter156)
              {
                oprot.writeString(_iter157);
              }
            }
          }
        }
      }
      if (struct.isSetSys_status()) {
        oprot.writeI64(struct.sys_status);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Top33Model struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.description = iprot.readString();
        struct.setDescriptionIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list158 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.data = new java.util.ArrayList<java.util.List<java.lang.String>>(_list158.size);
          java.util.List<java.lang.String> _elem159;
          for (int _i160 = 0; _i160 < _list158.size; ++_i160)
          {
            {
              org.apache.thrift.protocol.TList _list161 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem159 = new java.util.ArrayList<java.lang.String>(_list161.size);
              java.lang.String _elem162;
              for (int _i163 = 0; _i163 < _list161.size; ++_i163)
              {
                _elem162 = iprot.readString();
                _elem159.add(_elem162);
              }
            }
            struct.data.add(_elem159);
          }
        }
        struct.setDataIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list164 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.recentAdditions = new java.util.ArrayList<java.util.List<java.lang.String>>(_list164.size);
          java.util.List<java.lang.String> _elem165;
          for (int _i166 = 0; _i166 < _list164.size; ++_i166)
          {
            {
              org.apache.thrift.protocol.TList _list167 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem165 = new java.util.ArrayList<java.lang.String>(_list167.size);
              java.lang.String _elem168;
              for (int _i169 = 0; _i169 < _list167.size; ++_i169)
              {
                _elem168 = iprot.readString();
                _elem165.add(_elem168);
              }
            }
            struct.recentAdditions.add(_elem165);
          }
        }
        struct.setRecentAdditionsIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list170 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.recentRemovals = new java.util.ArrayList<java.util.List<java.lang.String>>(_list170.size);
          java.util.List<java.lang.String> _elem171;
          for (int _i172 = 0; _i172 < _list170.size; ++_i172)
          {
            {
              org.apache.thrift.protocol.TList _list173 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
              _elem171 = new java.util.ArrayList<java.lang.String>(_list173.size);
              java.lang.String _elem174;
              for (int _i175 = 0; _i175 < _list173.size; ++_i175)
              {
                _elem174 = iprot.readString();
                _elem171.add(_elem174);
              }
            }
            struct.recentRemovals.add(_elem171);
          }
        }
        struct.setRecentRemovalsIsSet(true);
      }
      if (incoming.get(4)) {
        struct.sys_status = iprot.readI64();
        struct.setSys_statusIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

