/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef won_CONSTANTS_H
#define won_CONSTANTS_H

#include "won_types.h"

namespace won {

class wonConstants {
 public:
  wonConstants();

};

extern const wonConstants g_won_constants;

} // namespace

#endif
