/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "won_constants.h"

namespace won {

const wonConstants g_won_constants;

wonConstants::wonConstants() {
}

} // namespace

